---

- name: Configure nova controller
  ini_file:
    dest: /etc/nova/nova.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    # APIs
    - section: DEFAULT
      option: enabled_apis
      value: 'osapi_compute,metadata'
    # Database
    - section: api_database
      option: connection
      value: '{{ openstack_nova_controller_nova_api_database_url }}'
    - section: database
      option: connection
      value: '{{ openstack_nova_controller_nova_database_url }}'
    # Messaging
    - section: DEFAULT
      option: rpc_backend
      value: rabbit
    - section: oslo_messaging_rabbit
      option: rabbit_host
      value: '{{ openstack_nova_controller_rabbit_hostname }}'
    - section: oslo_messaging_rabbit
      option: rabbit_userid
      value: '{{ openstack_nova_controller_rabbit_username }}'
    - section: oslo_messaging_rabbit
      option: rabbit_password
      value: '{{ openstack_nova_controller_rabbit_password }}'
    - section: oslo_messaging_rabbit
      option: rabbit_virtual_host
      value: '{{ openstack_nova_controller_rabbit_virtual_host }}'
    # Keystone
    - section: DEFAULT
      option: auth_strategy
      value: keystone
    - section: keystone_authtoken
      option: identity_uri
      value: >-
        {{- openstack_nova_controller_keystone_protocol }}://
        {{- openstack_nova_controller_keystone_hostname }}:
        {{- openstack_nova_controller_keystone_admin_port }}
    - section: keystone_authtoken
      option: auth_url
      value: >-
        {{- openstack_nova_controller_keystone_protocol }}://
        {{- openstack_nova_controller_keystone_hostname }}:
        {{- openstack_nova_controller_keystone_admin_port }}
    - section: keystone_authtoken
      option: auth_uri
      value: >-
        {{- openstack_nova_controller_keystone_protocol }}://
        {{- openstack_nova_controller_keystone_hostname }}:
        {{- openstack_nova_controller_keystone_port }}/v3
    - section: keystone_authtoken
      option: project_domain_name
      value: default
    - section: keystone_authtoken
      option: user_domain_name
      value: default
    - section: keystone_authtoken
      option: memcached_servers
      value: '{{ openstack_nova_controller_keystone_hostname }}:11211'
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: auth_version
      value: v3
    - section: keystone_authtoken
      option: username
      value: '{{ openstack_nova_controller_nova_user }}'
    - section: keystone_authtoken
      option: password
      value: '{{ openstack_nova_controller_nova_password }}'
    # Mgmt address
    - section: DEFAULT
      option: my_ip
      value: '{{ openstack_nova_controller_nova_my_ip }}'
    # Neutron
    - section: DEFAULT
      option: use_neutron
      value: True
    - section: DEFAULT
      option: firewall_driver
      value: nova.virt.firewall.NoopFirewallDriver
    - section: neutron
      option: url
      value: >-
        {{- openstack_nova_controller_neutron_protocol }}://
        {{- openstack_nova_controller_neutron_hostname }}:
        {{- openstack_nova_controller_neutron_port }}
    - section: neutron
      option: auth_url
      value: >-
        {{- openstack_nova_controller_keystone_protocol }}://
        {{- openstack_nova_controller_keystone_hostname }}:
        {{- openstack_nova_controller_keystone_admin_port }}
    - section: neutron
      option: auth_type
      value: password
    - section: neutron
      option: project_name
      value: service
    - section: neutron
      option: username
      value: '{{ openstack_nova_controller_neutron_username }}'
    - section: neutron
      option: password
      value: '{{ openstack_nova_controller_neutron_password }}'
    - section: neutron
      option: service_metadata_proxy
      value: True
    - section: neutron
      option: metadata_proxy_shared_secret
      value: '{{ openstack_nova_controller_neutron_metadata_secret }}'
    # VNC
    - section: vnc
      option: enabled
      value: True
    - section: vnc
      option: vncserver_listen
      value: 0.0.0.0
    - section: vnc
      option: vncserver_proxyclient_address
      value: '{{ openstack_nova_controller_vncserver_proxyclient_address }}'
    - section: vnc
      option: novncproxy_base_url
      value: '{{ openstack_nova_controller_novncproxy_base_url }}'
    # Glance
    - section: glance
      option: api_servers
      value: >-
        {{- openstack_nova_controller_glance_protocol }}://
        {{- openstack_nova_controller_glance_hostname }}:
        {{- openstack_nova_controller_glance_port }}
    # Oslo
    - section: oslo_concurrency
      option: lock_path
      value: /var/lib/nova/tmp
  notify:
    - Restart nova controller services

- name: Get current Nova database version
  command: 'nova-manage db version'
  always_run: True
  become: True
  become_user: 'nova'
  changed_when: openstack_nova_manage_db_version.stdout|int != openstack_nova_database_schema_version
  register: openstack_nova_manage_db_version

- name: Migrate Nova database to desired version
  command: 'nova-manage db sync {{ openstack_nova_database_schema_version }}'
  become: True
  become_user: 'nova'
  notify:
    - Restart nova controller services
  when: openstack_nova_manage_db_version|changed

- name: Get current Nova API database version
  command: 'nova-manage api_db version'
  always_run: True
  become: True
  become_user: 'nova'
  changed_when: openstack_nova_manage_api_db_version.stdout|int != openstack_nova_api_database_schema_version
  register: openstack_nova_manage_api_db_version

- name: Migrate Nova API database to desired version
  command: 'nova-manage api_db sync {{ openstack_nova_api_database_schema_version }}'
  become: True
  become_user: 'nova'
  notify:
    - Restart nova controller services
  when: openstack_nova_manage_api_db_version|changed
