---

- name: Install Nova controller packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
