---

- name: SANITY CHECK List nova instances
  shell: >-
    openstack
    --os-identity-api-version 3
    --os-auth-url
      {{ openstack_nova_controller_keystone_protocol }}://{{ openstack_nova_controller_keystone_hostname }}:{{ openstack_nova_controller_keystone_port }}/v3
    --os-project-name "{{ openstack_nova_controller_demo_project }}"
    --os-username "{{ openstack_nova_controller_demo_user }}"
    --os-auth-type password
    --os-password "{{ openstack_nova_controller_demo_pass }}"
    --os-user-domain-id default
    --os-project-domain-id default
    server list
  register: server_list_test
  changed_when: server_list_test.rc != 0

- debug: var=server_list_test.stdout_lines
