---

- name: Restart nova controller services
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - '{{ openstack_nova_controller_nova_api_service }}'
    - '{{ openstack_nova_controller_nova_conductor_service }}'
    - '{{ openstack_nova_controller_nova_consoleauth_service }}'
    - '{{ openstack_nova_controller_nova_novncproxy_service }}'
    - '{{ openstack_nova_controller_nova_scheduler_service }}'
