---

- name: Restart nova controller services
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - '{{ nova_api_service }}'
    - '{{ nova_conductor_service }}'
    - '{{ nova_consoleauth_service }}'
    - '{{ nova_novncproxy_service }}'
    - '{{ nova_scheduler_service }}'

- name: 'Sync nova database'
  command: 'nova-manage db sync'
  become: True
  become_user: 'nova'
  notify:
    - 'Restart nova controller services'

- name: 'Sync nova API database'
  command: 'nova-manage api_db sync'
  become: True
  become_user: 'nova'
  notify:
    - 'Restart nova controller services'
